sensor:
  ###################################################################
  #                                                                 #
  #          Definition von Sensoren für Paperless                  #
  #                                                                 #
  ###################################################################
  - state_topic: "paperless/post-consumption"
    name: "Paperless"
    value_template: "{{ value_json.file_name }}"
    payload_available: "online"
    payload_not_available: "offline"
    unique_id: 987654321
  - state_topic: "paperless/post-consumption"
    name: "paperless_id"
    value_template: "{{ value_json.id }}"
    payload_available: "online"
    payload_not_available: "offline"
  - state_topic: "paperless/post-consumption"
    name: "paperless_file_name"
    value_template: "{{ value_json.file_name }}"
    payload_available: "online"
    payload_not_available: "offline"
  - state_topic: "paperless/post-consumption"
    name: "paperless_created"
    value_template: "{{ as_datetime(value_json.created) }}"
    payload_available: "online"
    payload_not_available: "offline"
  - state_topic: "paperless/post-consumption"
    name: "Paperless_modified"
    value_template: "{{ as_datetime(value_json.modified) }}"
    payload_available: "online"
    payload_not_available: "offline"
  - state_topic: "paperless/post-consumption"
    name: "Paperless_added"
    value_template: "{{ as_datetime(value_json.added) }}"
    payload_available: "online"
    payload_not_available: "offline"
  - state_topic: "paperless/post-consumption"
    name: "Paperless_source_path"
    value_template: "{{ value_json.source_path }}"
    payload_available: "online"
    payload_not_available: "offline"
  - state_topic: "paperless/post-consumption"
    name: "Paperless_archive_path"
    value_template: "{{ value_json.archive_path }}"
    payload_available: "online"
    payload_not_available: "offline"
  - state_topic: "paperless/post-consumption"
    name: "Paperless_thumbnail_path"
    value_template: "{{ value_json.thumbnail_path }}"
    payload_available: "online"
    payload_not_available: "offline"  
  - state_topic: "paperless/post-consumption"
    name: "Paperless_download_url"
    value_template: "{{ value_json.download_url }}"
    payload_available: "online"
    payload_not_available: "offline"
  - state_topic: "paperless/post-consumption"
    name: "Paperless_thumbnail_url"
    value_template: "{{ value_json.thumbnail_url }}"
    payload_available: "online"
    payload_not_available: "offline"
  - state_topic: "paperless/post-consumption"
    name: "Paperless_correspondent"
    value_template: "{{ value_json.correspondent }}"
    payload_available: "online"
    payload_not_available: "offline"
  - state_topic: "paperless/post-consumption"
    name: "Paperless_tags"
    value_template: "{{ value_json.tags }}"
    payload_available: "online"
    payload_not_available: "offline"
  - state_topic: "paperless/post-consumption"
    name: "Paperless_original_filename"
    value_template: "{{ value_json.original_filename }}"
    payload_available: "online"
    payload_not_available: "offline"
  - state_topic: "paperless/post-consumption"
    name: "Paperless_task_id"
    value_template: "{{ value_json.task_id }}"
    payload_available: "online"
    payload_not_available: "offline"
